// Proxy.mjs frame: imports, arg rewriting, spawnSync, compress() dispatcher,
// stats reporting, and main execution. Handler functions are appended after
// this string and are available via JS function-declaration hoisting.

export const PROXY_FRAME = `#!/usr/bin/env node
// token-trim proxy - token-compression wrapper for agent subprocess commands
// Auto-generated by token-trim. Do not edit.

import { spawnSync } from 'node:child_process';
import net from 'node:net';
import path from 'node:path';

const cmd  = process.argv[2];
const args = process.argv.slice(3);
if (!cmd) process.exit(1);

const SELF_BIN = process.env.__TT_BIN_DIR_ENV__ ?? '';
const SOCKET_PATH = process.env.__TT_STATS_SOCKET_ENV__ ?? '';
const SEP         = process.platform === 'win32' ? ';' : ':';
const cleanPath   = (process.env.PATH ?? '').split(SEP).filter(d => d && d !== SELF_BIN).join(SEP);

// __TT_FULL_FLAG__ bypasses compression and returns raw output.
const FULL_FLAG = '__TT_FULL_FLAG__';
const wantFull  = args.includes(FULL_FLAG);
const cleanArgs = wantFull ? args.filter(a => a !== FULL_FLAG) : args;

// Rewrite args before running so we get compact output directly.
// Handler functions are defined later in this file - function declarations are hoisted.
const effectiveArgs = (!wantFull && cmd === 'git') ? rewriteGitArgs(cleanArgs) : cleanArgs;

// On Windows, spawnSync resolves binaries using Windows PATH which maps Unix
// tools (cat, find, ls, grep ...) to wrong Windows counterparts.  Running via
// 'sh' (always present via the git installer) gives proper POSIX resolution.
const spawnOpts = {
  stdio: ['inherit', 'pipe', 'pipe'],
  env: { ...process.env, PATH: cleanPath },
  maxBuffer: 10 * 1024 * 1024,
};
const result = process.platform === 'win32'
  ? spawnSync(
      'sh',
      ['-c', [cmd, ...effectiveArgs.map(function(a) {
        return "'" + String(a).replace(/'/g, "'\\\\''") + "'";
      })].join(' ')],
      spawnOpts,
    )
  : spawnSync(cmd, effectiveArgs, spawnOpts);

const rawStdout = result.stdout?.toString('utf8') ?? '';
const rawStderr = result.stderr?.toString('utf8') ?? '';

// ── compress dispatcher ───────────────────────────────────────────────────────

function compress(text, cmdName, cmdArgs) {
  if (!text) return text;
  let out = text;

  // Strip ANSI cursor-positioning and progress-bar carriage-return sequences
  out = out.replace(/\\x1b\\[\\d*;\\d*[Hf]/g, '');
  out = out.replace(/\\x1b\\[\\d*[ABCDEFGsu]/g, '');
  out = out.replace(/(\\r(?:\\x1b\\[[0-9;]*[A-Za-z])?[^\\n]{0,256}){4,}(\\r(?:\\x1b\\[[0-9;]*[A-Za-z])?[^\\n]{0,256})/g, '$2');

  const sub = cmdArgs[0] ?? '';

  if      (cmdName === 'tsc' || /TS\\d{4}:/.test(out))             out = condenseTsc(out);
  else if (cmdName === 'npm' || cmdName === 'pnpm' || cmdName === 'yarn') {
    if (sub === 'audit') out = condensePkgAudit(out);
    else                  out = stripPkgNoise(out);
  }
  else if (cmdName === 'grep' || cmdName === 'rg')                  out = groupGrep(out);
  else if (cmdName === 'cargo')                                     out = condenseCargo(out, sub);
  else if (cmdName === 'pytest')                                    out = condensePytest(out);
  else if (cmdName === 'mypy')                                      out = condenseMypy(out);
  else if (cmdName === 'ruff')                                      out = condenseRuff(out, cmdArgs);
  else if (cmdName === 'pip')                                       out = condensePip(out, cmdArgs);
  else if (cmdName === 'go' && sub === 'test')                      out = condenseGoTest(out);
  else if (cmdName === 'docker')                                    out = condenseDocker(out, cmdArgs);
  else if (cmdName === 'kubectl')                                   out = condenseKubectl(out, cmdArgs);
  else if (cmdName === 'curl')                                      out = condenseCurl(out);
  else if (cmdName === 'wget')                                      out = condenseWget(out);
  else if (cmdName === 'gh')                                        out = condenseGh(out);
  else if (cmdName === 'make')                                      out = condenseMake(out);
  else if (cmdName === 'rspec')                                     out = condenseRspec(out);
  else if (cmdName === 'rubocop')                                   out = condenseRubocop(out);
  else if (cmdName === 'rake')                                      out = condenseRake(out);
  else if (cmdName === 'vitest')                                    out = condenseVitest(out);
  else if (cmdName === 'jest')                                      out = condenseJest(out);
  else if (cmdName === 'playwright')                                out = condensePlaywright(out);
  else if (cmdName === 'prettier')                                  out = condensePrettier(out);
  else if (cmdName === 'eslint')                                    out = condenseEslint(out);
  else if (cmdName === 'next')                                      out = condenseNext(out);
  else if (cmdName === 'aws')                                       out = condenseAws(out);
  else if (cmdName === 'psql')                                      out = condensePsql(out);
  else if (cmdName === 'golangci-lint')                             out = condenseGolangci(out);
  else if (cmdName === 'jq')                                        out = condenseJq(out);
  else if (cmdName === 'bun') {
    if (sub === 'test' || sub === 'run') out = condenseBunTest(out);
    else                                  out = condenseBunInstall(out);
  }
  else if (cmdName === 'terraform' || cmdName === 'tofu')           out = condenseTerraform(out, sub);
  else if (cmdName === 'mvn')                                       out = condenseMvn(out);
  else if (cmdName === 'gradle')                                    out = condenseGradle(out);
  else if (cmdName === 'dotnet')                                    out = condenseDotnet(out, sub);
  else if (cmdName === 'ls')                                        out = condenseLs(out);
  else if (cmdName === 'find')                                      out = condenseFind(out);
  else if (cmdName === 'git') {
    if (sub === 'diff' || sub === 'show' || /^(diff --|--- a\\/|@@ )/m.test(out))
      out = condenseDiff(out);
    else if (sub === 'log')    out = condenseGitLog(out);
    else if (sub === 'status') out = condenseGitStatus(out);
  }
  else if (cmdName === 'cat' || cmdName === 'head' || cmdName === 'tail')
    out = aggressiveStrip(out, detectLang(cmdArgs[0] ?? ''));

  out = out.split('\\n').map(l => l.replace(/[ \\t]+$/, '')).join('\\n');
  out = out.replace(/\\n{3,}/g, '\\n\\n');
  return out.trim();
}

// ── stats reporting ───────────────────────────────────────────────────────────

function reportSavings(displayCmd, savedBytes, originalBytes) {
  if (!SOCKET_PATH || savedBytes <= 0) return;
  try {
    const sock = net.createConnection(SOCKET_PATH);
    sock.on('connect', () => { sock.end(JSON.stringify({ cmd: displayCmd, savedBytes, originalBytes }) + '\\n'); });
    sock.on('error', () => {});
  } catch {}
}

// ── main ──────────────────────────────────────────────────────────────────────

const compressed = wantFull ? rawStdout.trim() : compress(rawStdout, cmd, effectiveArgs);
const originalBytes = Buffer.byteLength(rawStdout, 'utf8');
const savedBytes = Math.max(0, originalBytes - Buffer.byteLength(compressed, 'utf8'));

process.stdout.write(compressed);
if (rawStderr) process.stderr.write(rawStderr);

// Hint on stderr when significant compression occurred (never clutters stdout)
const HINT_CMDS = new Set(['jq','git','cat','head','tail','curl','wget','kubectl','docker','aws','psql','grep','rg','find','ls','terraform','tofu']);
if (!wantFull && savedBytes > __TT_HINT_MIN__ && HINT_CMDS.has(cmd)) {
  process.stderr.write('\\n[__TT_HINT_LABEL__] instruction (not output): compressed to save tokens; re-run with __TT_FULL_FLAG__ for the full output, do not switch commands.\\n');
}

const subCmd = effectiveArgs[0] ?? '';
const displayCmd = subCmd ? cmd + ' ' + subCmd : cmd;
reportSavings(displayCmd, savedBytes, originalBytes);
process.exitCode = result.status ?? 0;

// ── handler functions (hoisted - can be referenced above) ─────────────────────
`
